export type McpToolScope = "read" | "write";
export type McpOAuthScope = McpToolScope | "offline_access";

export const MCP_TOOL_SCOPES = {
  get_project: "read",
  get_project_entitlements: "read",
  update_project: "write",
  get_custom_css: "read",
  set_custom_css: "write",
  delete_custom_css: "write",
  upload_project_asset: "write",
  delete_project_asset: "write",
  list_bookings: "read",
  get_booking: "read",
  get_available_slots: "read",
  create_booking: "write",
  cancel_booking: "write",
  confirm_booking: "write",
  decline_booking: "write",
  get_booking_form_response: "read",
  list_event_types: "read",
  get_event_type: "read",
  create_event_type: "write",
  update_event_type: "write",
  delete_event_type: "write",
  list_project_calendars: "read",
  get_event_type_calendars: "read",
  update_event_type_calendars: "write",
  list_schedules: "read",
  get_schedule: "read",
  create_schedule: "write",
  update_schedule: "write",
  delete_schedule: "write",
  set_schedule_rules: "write",
  add_schedule_override: "write",
  delete_schedule_override: "write",
  list_contacts: "read",
  get_contact: "read",
  create_contact: "write",
  update_contact: "write",
  set_contact_next_action: "write",
  complete_contact_next_action: "write",
  delete_contact: "write",
  list_contact_tags: "read",
  get_contact_tag: "read",
  create_contact_tag: "write",
  update_contact_tag: "write",
  delete_contact_tag: "write",
  add_tag_to_contact: "write",
  remove_tag_from_contact: "write",
  get_contact_activity: "read",
  list_contact_views: "read",
  create_contact_view: "write",
  update_contact_view: "write",
  delete_contact_view: "write",
  import_contacts: "write",
  set_contact_stage: "write",
  enrich_contact: "write",
  seed_contact_pipeline: "write",
  list_forms: "read",
  get_form: "read",
  create_form: "write",
  update_form: "write",
  delete_form: "write",
  create_form_step: "write",
  update_form_step: "write",
  delete_form_step: "write",
  reorder_form_steps: "write",
  create_form_field: "write",
  update_form_field: "write",
  delete_form_field: "write",
  reorder_form_fields: "write",
  list_form_responses: "read",
  get_form_response: "read",
  get_form_response_file: "read",
  delete_form_response: "write",
  list_workflows: "read",
  get_workflow: "read",
  create_workflow: "write",
  update_workflow: "write",
  delete_workflow: "write",
  create_workflow_step: "write",
  update_workflow_step: "write",
  delete_workflow_step: "write",
  reorder_workflow_steps: "write",
  list_workflow_runs: "read",
  get_workflow_run: "read",
  trigger_workflow: "write",
  test_workflow: "write",
  list_recent_activity: "read",
  get_analytics_filters: "read",
  get_analytics_overview: "read",
  get_booking_funnel_analytics: "read",
  get_form_funnel_analytics: "read",
  list_analytics_integrations: "read",
  configure_analytics_integration: "write",
} as const satisfies Record<string, McpToolScope>;

export type McpToolName = keyof typeof MCP_TOOL_SCOPES;

export interface McpToolDiscovery {
  domain: string;
  title: string;
  destructiveHint?: boolean;
  idempotentHint?: boolean;
  openWorldHint?: boolean;
}

export const MCP_TOOL_DISCOVERY = {
  get_project: { domain: "Project", title: "Get project" },
  get_project_entitlements: {
    domain: "Project",
    title: "Get project entitlements",
  },
  update_project: {
    domain: "Project",
    title: "Update project",
    idempotentHint: true,
  },
  get_custom_css: { domain: "Project", title: "Get Custom CSS" },
  set_custom_css: {
    domain: "Project",
    title: "Set Custom CSS",
    idempotentHint: true,
  },
  delete_custom_css: {
    domain: "Project",
    title: "Delete Custom CSS",
    destructiveHint: true,
    idempotentHint: true,
  },
  upload_project_asset: {
    domain: "Project",
    title: "Upload project asset",
    destructiveHint: false,
  },
  delete_project_asset: {
    domain: "Project",
    title: "Delete project asset",
    destructiveHint: true,
    idempotentHint: true,
  },
  list_bookings: { domain: "Bookings", title: "List bookings" },
  get_booking: { domain: "Bookings", title: "Get booking" },
  get_available_slots: {
    domain: "Bookings",
    title: "Get available slots",
    openWorldHint: true,
  },
  create_booking: {
    domain: "Bookings",
    title: "Create booking",
    destructiveHint: false,
    openWorldHint: true,
  },
  cancel_booking: {
    domain: "Bookings",
    title: "Cancel booking",
    destructiveHint: true,
    openWorldHint: true,
  },
  confirm_booking: {
    domain: "Bookings",
    title: "Confirm booking",
    openWorldHint: true,
  },
  decline_booking: {
    domain: "Bookings",
    title: "Decline booking",
    destructiveHint: true,
    openWorldHint: true,
  },
  get_booking_form_response: {
    domain: "Bookings",
    title: "Get booking form response",
  },
  list_event_types: { domain: "Event types", title: "List event types" },
  get_event_type: { domain: "Event types", title: "Get event type" },
  create_event_type: {
    domain: "Event types",
    title: "Create event type",
    destructiveHint: false,
  },
  update_event_type: {
    domain: "Event types",
    title: "Update event type",
    idempotentHint: true,
  },
  delete_event_type: {
    domain: "Event types",
    title: "Delete event type",
    destructiveHint: true,
  },
  list_project_calendars: {
    domain: "Calendars",
    title: "List project calendars",
    openWorldHint: true,
  },
  get_event_type_calendars: {
    domain: "Calendars",
    title: "Get event type calendars",
  },
  update_event_type_calendars: {
    domain: "Calendars",
    title: "Update event type calendars",
    idempotentHint: true,
  },
  list_schedules: { domain: "Schedules", title: "List schedules" },
  get_schedule: { domain: "Schedules", title: "Get schedule" },
  create_schedule: {
    domain: "Schedules",
    title: "Create schedule",
    destructiveHint: false,
  },
  update_schedule: {
    domain: "Schedules",
    title: "Update schedule",
    idempotentHint: true,
  },
  delete_schedule: {
    domain: "Schedules",
    title: "Delete schedule",
    destructiveHint: true,
  },
  set_schedule_rules: {
    domain: "Schedules",
    title: "Set schedule rules",
    destructiveHint: true,
    idempotentHint: true,
  },
  add_schedule_override: {
    domain: "Schedules",
    title: "Add schedule override",
    destructiveHint: false,
  },
  delete_schedule_override: {
    domain: "Schedules",
    title: "Delete schedule override",
    destructiveHint: true,
    idempotentHint: true,
  },
  list_contacts: { domain: "Contacts", title: "List contacts" },
  get_contact: { domain: "Contacts", title: "Get contact" },
  create_contact: {
    domain: "Contacts",
    title: "Create contact",
    destructiveHint: false,
    openWorldHint: true,
  },
  update_contact: {
    domain: "Contacts",
    title: "Update contact",
    idempotentHint: true,
  },
  set_contact_next_action: {
    domain: "Contacts",
    title: "Set contact next action",
  },
  complete_contact_next_action: {
    domain: "Contacts",
    title: "Complete contact next action",
    idempotentHint: true,
  },
  delete_contact: {
    domain: "Contacts",
    title: "Delete contact",
    destructiveHint: true,
  },
  list_contact_tags: { domain: "Tags", title: "List contact tags" },
  get_contact_tag: { domain: "Tags", title: "Get contact tag" },
  create_contact_tag: {
    domain: "Tags",
    title: "Create contact tag",
    destructiveHint: false,
  },
  update_contact_tag: {
    domain: "Tags",
    title: "Update contact tag",
    idempotentHint: true,
  },
  delete_contact_tag: {
    domain: "Tags",
    title: "Delete contact tag",
    destructiveHint: true,
  },
  add_tag_to_contact: {
    domain: "Tags",
    title: "Add tag to contact",
    destructiveHint: false,
    idempotentHint: true,
    openWorldHint: true,
  },
  remove_tag_from_contact: {
    domain: "Tags",
    title: "Remove tag from contact",
    destructiveHint: true,
    idempotentHint: true,
  },
  get_contact_activity: { domain: "Contacts", title: "Get contact activity" },
  list_contact_views: { domain: "CRM", title: "List contact views" },
  create_contact_view: {
    domain: "CRM",
    title: "Create contact view",
    destructiveHint: false,
  },
  update_contact_view: {
    domain: "CRM",
    title: "Update contact view",
    idempotentHint: true,
  },
  delete_contact_view: {
    domain: "CRM",
    title: "Delete contact view",
    destructiveHint: true,
  },
  import_contacts: {
    domain: "CRM",
    title: "Import contacts",
    destructiveHint: false,
    openWorldHint: true,
  },
  set_contact_stage: {
    domain: "CRM",
    title: "Set contact stage",
    idempotentHint: true,
  },
  enrich_contact: {
    domain: "CRM",
    title: "Enrich contact",
    openWorldHint: true,
  },
  seed_contact_pipeline: {
    domain: "CRM",
    title: "Seed contact pipeline",
    destructiveHint: false,
    idempotentHint: true,
  },
  list_forms: { domain: "Forms", title: "List forms" },
  get_form: { domain: "Forms", title: "Get form" },
  create_form: {
    domain: "Forms",
    title: "Create form",
    destructiveHint: false,
  },
  update_form: {
    domain: "Forms",
    title: "Update form",
    idempotentHint: true,
  },
  delete_form: {
    domain: "Forms",
    title: "Delete form",
    destructiveHint: true,
  },
  create_form_step: {
    domain: "Forms",
    title: "Create form step",
    destructiveHint: false,
  },
  update_form_step: {
    domain: "Forms",
    title: "Update form step",
    idempotentHint: true,
  },
  delete_form_step: {
    domain: "Forms",
    title: "Delete form step",
    destructiveHint: true,
  },
  reorder_form_steps: {
    domain: "Forms",
    title: "Reorder form steps",
    idempotentHint: true,
  },
  create_form_field: {
    domain: "Forms",
    title: "Create form field",
    destructiveHint: false,
  },
  update_form_field: {
    domain: "Forms",
    title: "Update form field",
    idempotentHint: true,
  },
  delete_form_field: {
    domain: "Forms",
    title: "Delete form field",
    destructiveHint: true,
  },
  reorder_form_fields: {
    domain: "Forms",
    title: "Reorder form fields",
    idempotentHint: true,
  },
  list_form_responses: { domain: "Forms", title: "List form responses" },
  get_form_response: { domain: "Forms", title: "Get form response" },
  get_form_response_file: {
    domain: "Forms",
    title: "Get form response file",
  },
  delete_form_response: {
    domain: "Forms",
    title: "Delete form response",
    destructiveHint: true,
  },
  list_workflows: { domain: "Workflows", title: "List workflows" },
  get_workflow: { domain: "Workflows", title: "Get workflow" },
  create_workflow: {
    domain: "Workflows",
    title: "Create workflow",
    destructiveHint: false,
  },
  update_workflow: {
    domain: "Workflows",
    title: "Update workflow",
    idempotentHint: true,
  },
  delete_workflow: {
    domain: "Workflows",
    title: "Delete workflow",
    destructiveHint: true,
  },
  create_workflow_step: {
    domain: "Workflows",
    title: "Create workflow step",
    destructiveHint: false,
  },
  update_workflow_step: {
    domain: "Workflows",
    title: "Update workflow step",
    idempotentHint: true,
  },
  delete_workflow_step: {
    domain: "Workflows",
    title: "Delete workflow step",
    destructiveHint: true,
  },
  reorder_workflow_steps: {
    domain: "Workflows",
    title: "Reorder workflow steps",
    idempotentHint: true,
  },
  list_workflow_runs: { domain: "Workflows", title: "List workflow runs" },
  get_workflow_run: { domain: "Workflows", title: "Get workflow run" },
  trigger_workflow: {
    domain: "Workflows",
    title: "Trigger workflow",
    destructiveHint: false,
    openWorldHint: true,
  },
  test_workflow: {
    domain: "Workflows",
    title: "Test workflow",
    destructiveHint: false,
    openWorldHint: true,
  },
  list_recent_activity: { domain: "Activity", title: "List recent activity" },
  get_analytics_filters: {
    domain: "Analytics",
    title: "Get analytics filters",
  },
  get_analytics_overview: {
    domain: "Analytics",
    title: "Get analytics overview",
  },
  get_booking_funnel_analytics: {
    domain: "Analytics",
    title: "Get booking funnel analytics",
  },
  get_form_funnel_analytics: {
    domain: "Analytics",
    title: "Get form funnel analytics",
  },
  list_analytics_integrations: {
    domain: "Analytics",
    title: "List analytics integrations",
  },
  configure_analytics_integration: {
    domain: "Analytics",
    title: "Configure analytics integration",
    idempotentHint: true,
  },
} as const satisfies Record<McpToolName, McpToolDiscovery>;
