export type McpToolScope = "read" | "write";
export type McpOAuthScope = McpToolScope | "offline_access";

export const MCP_TOOL_SCOPES = {
  list_bookings: "read",
  get_booking: "read",
  get_available_slots: "read",
  create_booking: "write",
  cancel_booking: "write",
  confirm_booking: "write",
  decline_booking: "write",
  list_event_types: "read",
  get_event_type: "read",
  create_event_type: "write",
  update_event_type: "write",
  list_schedules: "read",
  get_schedule: "read",
  list_contacts: "read",
  get_contact: "read",
  create_contact: "write",
  update_contact: "write",
  set_contact_next_action: "write",
  complete_contact_next_action: "write",
  delete_contact: "write",
  list_contact_tags: "read",
  get_contact_tag: "read",
  create_contact_tag: "write",
  update_contact_tag: "write",
  delete_contact_tag: "write",
  add_tag_to_contact: "write",
  remove_tag_from_contact: "write",
  get_contact_activity: "read",
  list_forms: "read",
  get_form: "read",
  create_form: "write",
  update_form: "write",
  list_form_responses: "read",
  list_workflows: "read",
  get_workflow: "read",
  get_analytics_overview: "read",
  get_booking_funnel_analytics: "read",
  get_form_funnel_analytics: "read",
  list_analytics_integrations: "read",
  configure_analytics_integration: "write",
} as const satisfies Record<string, McpToolScope>;

export type McpToolName = keyof typeof MCP_TOOL_SCOPES;
